//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 08:21:47 AM IST 
//


package com.jeet.api;

import java.io.Serializable;

import jakarta.persistence.*;


@Entity
@Cacheable
public class Ticket implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 915391445865843223L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    protected int ticketId;
    protected int price;
    protected double tax;
    protected String seats_seatNumber;
    protected String seats_seatRow;
    
    @Column(insertable=false, updatable=false)
    protected String screen_screenId;
   
    @OneToOne(fetch=FetchType.EAGER)
    protected Screen screen;
    @ManyToOne(fetch=FetchType.EAGER)
    protected Seats seats;
	
    @Transient
    protected String movie_name;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchase_purchaseId")
	protected Purchase purchase;

	@Column(insertable=false, updatable=false)
	protected String purchase_purchaseId;
    
    public Ticket() {
    }
    
    public Ticket(int ticketId, int price, double tax, String seats_seatNumber, String seats_seatRow, String screen_screenId, String movie_name) {
    	this.ticketId = ticketId;
    	this.price = price;
    	this.tax = tax;
    	//this.movie_name = movie_name;
    	this.seats_seatNumber = seats_seatNumber;
    	this.seats_seatRow = seats_seatRow;
    }

    /**
     * Gets the value of the ticketId property.
     * 
     */
    public int getTicketId() {
        return ticketId;
    }

    /**
     * Sets the value of the ticketId property.
     * 
     */
    public void setTicketId(int value) {
        this.ticketId = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(int value) {
        this.price = value;
    }
    
    /**
     * Gets the value of the tax property.
     * 
     */
    public double getTax() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     */
    public void setTax(double value) {
        this.tax = value;
    }

    /**
     * Gets the value of the screen property.
     * 
     * @return
     *     possible object is
     *     {@link Screen }
     *     
     */
    public Screen getScreen() {
        return screen;
    }

    /**
     * Sets the value of the screen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Screen }
     *     
     */
    public void setScreen(Screen value) {
        this.screen = value;
    }

	/**
	 * @return the seats
	 */
	public Seats getSeats() {
		return seats;
	}

	/**
	 * @param seats the seats to set
	 */
	public void setSeats(Seats seats) {
		this.seats = seats;
	}

	/**
	 * @return the seats_seatNumber
	 */
	public String getSeats_seatNumber() {
		return seats_seatNumber;
	}

	/**
	 * @param seats_seatNumber the seats_seatNumber to set
	 */
	public void setSeats_seatNumber(String seats_seatNumber) {
		this.seats_seatNumber = seats_seatNumber;
	}

	/**
	 * @return the seats_seatRow
	 */
	public String getSeats_seatRow() {
		return seats_seatRow;
	}

	/**
	 * @param seats_seatRow the seats_seatRow to set
	 */
	public void setSeats_seatRow(String seats_seatRow) {
		this.seats_seatRow = seats_seatRow;
	}

	/**
	 * @return the screen_screenId
	 */
	public String getScreen_screenId() {
		return screen_screenId;
	}

	/**
	 * @param screen_screenId the screen_screenId to set
	 */
	public void setScreen_screenId(String screen_screenId) {
		this.screen_screenId = screen_screenId;
	}
	
	/**
	 * @return the movie_name
	 */
	public String getMovie_name() {
		return movie_name;
	}

	/**
	 * @param movie_name the movie_name to set
	 */
	public void setMovie_name(String movie_name) {
		this.movie_name = movie_name;
	}

	/**
	 * @return the purchaseHistory
	 */
	public Purchase getPurchase() {
		return purchase;
	}

	/**
	 * @param the purchase to set
	 */
	public void setPurchase(Purchase purchase) {
		this.purchase = purchase;
	}

}
